/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as StudyAbroadRouteImport } from './routes/study-abroad'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MigrationRouteImport } from './routes/migration'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyAbroadCountryRouteImport } from './routes/study-abroad.$country'
import { Route as MigrationProgramRouteImport } from './routes/migration.$program'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadRoute = StudyAbroadRouteImport.update({
  id: '/study-abroad',
  path: '/study-abroad',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationRoute = MigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadCountryRoute = StudyAbroadCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => StudyAbroadRoute,
} as any)
const MigrationProgramRoute = MigrationProgramRouteImport.update({
  id: '/$program',
  path: '/$program',
  getParentRoute: () => MigrationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/migration': typeof MigrationRouteWithChildren
  '/services': typeof ServicesRoute
  '/study-abroad': typeof StudyAbroadRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/migration/$program': typeof MigrationProgramRoute
  '/study-abroad/$country': typeof StudyAbroadCountryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/migration': typeof MigrationRouteWithChildren
  '/services': typeof ServicesRoute
  '/study-abroad': typeof StudyAbroadRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/migration/$program': typeof MigrationProgramRoute
  '/study-abroad/$country': typeof StudyAbroadCountryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/migration': typeof MigrationRouteWithChildren
  '/services': typeof ServicesRoute
  '/study-abroad': typeof StudyAbroadRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/migration/$program': typeof MigrationProgramRoute
  '/study-abroad/$country': typeof StudyAbroadCountryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/migration'
    | '/services'
    | '/study-abroad'
    | '/testimonials'
    | '/migration/$program'
    | '/study-abroad/$country'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/migration'
    | '/services'
    | '/study-abroad'
    | '/testimonials'
    | '/migration/$program'
    | '/study-abroad/$country'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/migration'
    | '/services'
    | '/study-abroad'
    | '/testimonials'
    | '/migration/$program'
    | '/study-abroad/$country'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  MigrationRoute: typeof MigrationRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  StudyAbroadRoute: typeof StudyAbroadRouteWithChildren
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad': {
      id: '/study-abroad'
      path: '/study-abroad'
      fullPath: '/study-abroad'
      preLoaderRoute: typeof StudyAbroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/$country': {
      id: '/study-abroad/$country'
      path: '/$country'
      fullPath: '/study-abroad/$country'
      preLoaderRoute: typeof StudyAbroadCountryRouteImport
      parentRoute: typeof StudyAbroadRoute
    }
    '/migration/$program': {
      id: '/migration/$program'
      path: '/$program'
      fullPath: '/migration/$program'
      preLoaderRoute: typeof MigrationProgramRouteImport
      parentRoute: typeof MigrationRoute
    }
  }
}

interface MigrationRouteChildren {
  MigrationProgramRoute: typeof MigrationProgramRoute
}

const MigrationRouteChildren: MigrationRouteChildren = {
  MigrationProgramRoute: MigrationProgramRoute,
}

const MigrationRouteWithChildren = MigrationRoute._addFileChildren(
  MigrationRouteChildren,
)

interface StudyAbroadRouteChildren {
  StudyAbroadCountryRoute: typeof StudyAbroadCountryRoute
}

const StudyAbroadRouteChildren: StudyAbroadRouteChildren = {
  StudyAbroadCountryRoute: StudyAbroadCountryRoute,
}

const StudyAbroadRouteWithChildren = StudyAbroadRoute._addFileChildren(
  StudyAbroadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  MigrationRoute: MigrationRouteWithChildren,
  ServicesRoute: ServicesRoute,
  StudyAbroadRoute: StudyAbroadRouteWithChildren,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
