/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteTestimonialsRouteImport } from './routes/_site/testimonials'
import { Route as SiteStudyAbroadRouteImport } from './routes/_site/study-abroad'
import { Route as SiteServicesRouteImport } from './routes/_site/services'
import { Route as SiteMigrationRouteImport } from './routes/_site/migration'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteStudyAbroadCountryRouteImport } from './routes/_site/study-abroad.$country'
import { Route as SiteServicesVisaRouteImport } from './routes/_site/services.$visa'
import { Route as SiteMigrationProgramRouteImport } from './routes/_site/migration.$program'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTestimonialsRoute = SiteTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStudyAbroadRoute = SiteStudyAbroadRouteImport.update({
  id: '/study-abroad',
  path: '/study-abroad',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMigrationRoute = SiteMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStudyAbroadCountryRoute = SiteStudyAbroadCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => SiteStudyAbroadRoute,
} as any)
const SiteServicesVisaRoute = SiteServicesVisaRouteImport.update({
  id: '/$visa',
  path: '/$visa',
  getParentRoute: () => SiteServicesRoute,
} as any)
const SiteMigrationProgramRoute = SiteMigrationProgramRouteImport.update({
  id: '/$program',
  path: '/$program',
  getParentRoute: () => SiteMigrationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/migration': typeof SiteMigrationRouteWithChildren
  '/services': typeof SiteServicesRouteWithChildren
  '/study-abroad': typeof SiteStudyAbroadRouteWithChildren
  '/testimonials': typeof SiteTestimonialsRoute
  '/migration/$program': typeof SiteMigrationProgramRoute
  '/services/$visa': typeof SiteServicesVisaRoute
  '/study-abroad/$country': typeof SiteStudyAbroadCountryRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/migration': typeof SiteMigrationRouteWithChildren
  '/services': typeof SiteServicesRouteWithChildren
  '/study-abroad': typeof SiteStudyAbroadRouteWithChildren
  '/testimonials': typeof SiteTestimonialsRoute
  '/': typeof SiteIndexRoute
  '/migration/$program': typeof SiteMigrationProgramRoute
  '/services/$visa': typeof SiteServicesVisaRoute
  '/study-abroad/$country': typeof SiteStudyAbroadCountryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/migration': typeof SiteMigrationRouteWithChildren
  '/_site/services': typeof SiteServicesRouteWithChildren
  '/_site/study-abroad': typeof SiteStudyAbroadRouteWithChildren
  '/_site/testimonials': typeof SiteTestimonialsRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/migration/$program': typeof SiteMigrationProgramRoute
  '/_site/services/$visa': typeof SiteServicesVisaRoute
  '/_site/study-abroad/$country': typeof SiteStudyAbroadCountryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/migration'
    | '/services'
    | '/study-abroad'
    | '/testimonials'
    | '/migration/$program'
    | '/services/$visa'
    | '/study-abroad/$country'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/migration'
    | '/services'
    | '/study-abroad'
    | '/testimonials'
    | '/'
    | '/migration/$program'
    | '/services/$visa'
    | '/study-abroad/$country'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/migration'
    | '/_site/services'
    | '/_site/study-abroad'
    | '/_site/testimonials'
    | '/_site/'
    | '/_site/migration/$program'
    | '/_site/services/$visa'
    | '/_site/study-abroad/$country'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/testimonials': {
      id: '/_site/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof SiteTestimonialsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/study-abroad': {
      id: '/_site/study-abroad'
      path: '/study-abroad'
      fullPath: '/study-abroad'
      preLoaderRoute: typeof SiteStudyAbroadRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/migration': {
      id: '/_site/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof SiteMigrationRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/study-abroad/$country': {
      id: '/_site/study-abroad/$country'
      path: '/$country'
      fullPath: '/study-abroad/$country'
      preLoaderRoute: typeof SiteStudyAbroadCountryRouteImport
      parentRoute: typeof SiteStudyAbroadRoute
    }
    '/_site/services/$visa': {
      id: '/_site/services/$visa'
      path: '/$visa'
      fullPath: '/services/$visa'
      preLoaderRoute: typeof SiteServicesVisaRouteImport
      parentRoute: typeof SiteServicesRoute
    }
    '/_site/migration/$program': {
      id: '/_site/migration/$program'
      path: '/$program'
      fullPath: '/migration/$program'
      preLoaderRoute: typeof SiteMigrationProgramRouteImport
      parentRoute: typeof SiteMigrationRoute
    }
  }
}

interface SiteMigrationRouteChildren {
  SiteMigrationProgramRoute: typeof SiteMigrationProgramRoute
}

const SiteMigrationRouteChildren: SiteMigrationRouteChildren = {
  SiteMigrationProgramRoute: SiteMigrationProgramRoute,
}

const SiteMigrationRouteWithChildren = SiteMigrationRoute._addFileChildren(
  SiteMigrationRouteChildren,
)

interface SiteServicesRouteChildren {
  SiteServicesVisaRoute: typeof SiteServicesVisaRoute
}

const SiteServicesRouteChildren: SiteServicesRouteChildren = {
  SiteServicesVisaRoute: SiteServicesVisaRoute,
}

const SiteServicesRouteWithChildren = SiteServicesRoute._addFileChildren(
  SiteServicesRouteChildren,
)

interface SiteStudyAbroadRouteChildren {
  SiteStudyAbroadCountryRoute: typeof SiteStudyAbroadCountryRoute
}

const SiteStudyAbroadRouteChildren: SiteStudyAbroadRouteChildren = {
  SiteStudyAbroadCountryRoute: SiteStudyAbroadCountryRoute,
}

const SiteStudyAbroadRouteWithChildren = SiteStudyAbroadRoute._addFileChildren(
  SiteStudyAbroadRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteMigrationRoute: typeof SiteMigrationRouteWithChildren
  SiteServicesRoute: typeof SiteServicesRouteWithChildren
  SiteStudyAbroadRoute: typeof SiteStudyAbroadRouteWithChildren
  SiteTestimonialsRoute: typeof SiteTestimonialsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteMigrationRoute: SiteMigrationRouteWithChildren,
  SiteServicesRoute: SiteServicesRouteWithChildren,
  SiteStudyAbroadRoute: SiteStudyAbroadRouteWithChildren,
  SiteTestimonialsRoute: SiteTestimonialsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
